# Multi-Binary Application Example
# Demonstrates building both CLI and GUI applications in a single release

version: 2

project_name: secretr
cleanup_dist_dirs: true

versioning:
  template: '{{ if .IsSnapshot }}{{ .OriginalVersion }}{{ else }}{{ .Version }}{{ end }}'

defaults:
  homepage: https://github.com/verishore/secretr
  description: A multi-binary application with CLI and GUI components
  license: MIT
  maintainer: developer@verishore.com

env:
  - GO111MODULE=on

# Define multiple builds: CLI tool and GUI application
builds:
  # CLI binary - installed to /usr/bin, available in PATH
  - id: cli
    main: ./cmd
    binary: secretr
    type: cli  # CLI type installs to system PATH
    obfuscation:
      enabled: true
      tool: garble
      flags:
        - -literals
        - -tiny
        - -debug=false
        - -seed=random
      env:
        - GARBLE_SEED=random
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0

  # GUI binary - installed as desktop application with menu entry
  # CGO is enabled for GUI because Fyne requires it
  # NOTE: Cross-compiling GUI apps with Fyne requires platform SDK headers.
  # - Windows: Works with zig cross-compiler
  # - macOS: Requires osxcross with macOS SDK
  # - Linux ARM64: Requires cross-compiled X11/GL dev headers
  # For full cross-platform GUI builds, use fyne-cross or build on each platform.
  - id: gui
    main: ./gui/cmd
    binary: secretr-gui
    type: gui  # GUI type creates desktop entries and app bundles
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Cross-compiled GUI builds are complex - build natively for macOS targets
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath
    # Enable CGO for Fyne GUI
    cgo:
      enabled: true
      # Cross-compilers for different platforms
      # Zig is recommended as a universal cross-compiler
      cross_compilers:
        windows_amd64:
          cc: zig cc -target x86_64-windows-gnu
          cxx: zig c++ -target x86_64-windows-gnu
    # GUI-specific metadata
    gui:
      name: "Secretr"
      comment: "Secretr GUI - A graphical interface for Secretr"
      generic_name: "Application Manager"
      categories:
        - Utility
        - Development
      keywords:
        - secretr
        - utility
        - gui
      startup_notify: true
      terminal: false
      mime_types:
        - application/x-secretr
      # macOS specific
      macos:
        bundle_id: "com.verishore.secretr"
        minimum_system_version: "10.13"
        high_resolution_capable: true
        info_plist:
          NSHumanReadableCopyright: "Copyright © 2025 Verishore LLC"
      # Windows specific
      windows:
        start_menu_folder: "Secretr"
        desktop_shortcut: true
        file_associations:
          - extension: ".secretr"
            description: "Secretr Document"

# Archives for distribution
archives:
  - id: cli-archive
    builds:
      - cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

  - id: gui-archive
    builds:
      - gui
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

# Linux packages - includes both CLI and GUI
nfpms:
  - id: all-packages
    package_name: secretr
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Verishore LLC
    maintainer: developer@verishore.com
    description: |
      Secretr - A multi-binary application
      Includes:
        - secretr: Command-line interface
        - secretr-gui: Graphical user interface
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    # The GUI binary will automatically get a .desktop file generated
    contents:
      # Additional config files
      - src: ./config.verishore.yaml
        dst: /etc/secretr/config.yaml
        type: config|noreplace
    # Dependencies vary by package format:
    # - deb: libgtk-3-0, libgl1
    # - rpm: gtk3, mesa-libGL
    # - apk: gtk+3.0, mesa-gl
    overrides:
      deb:
        dependencies:
          - libgtk-3-0
          - libgl1
      rpm:
        dependencies:
          - gtk3
          - mesa-libGL
      apk:
        dependencies:
          - gtk+3.0
          - mesa-gl
    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh

# macOS App Bundle for GUI
app_bundles:
  - id: gui-app
    builds:
      - gui
    name: "Secretr"
    identifier: "com.verishore.secretr"
    category: "public.app-category.utilities"
    high_resolution_capable: true
    minimum_system_version: "10.13"
    info_plist:
      NSHumanReadableCopyright: "Copyright © 2025 Verishore LLC"
      CFBundleShortVersionString: "{{ .Version }}"

# macOS DMG with App Bundle
dmgs:
  - id: gui-dmg
    builds:
      - gui
    name: "Secretr"
    name_template: "{{ .ProjectName }}_{{ .Version }}_macOS"
    title: "Secretr {{ .Version }}"
    window_size:
      width: 660
      height: 400
    contents:
      - type: app
        path: "Secretr.app"
      - type: link
        path: /Applications

# macOS PKG for GUI
pkgs:
  - id: gui-pkg
    builds:
      - gui
      - cli
    name: "Secretr"
    identifier: "com.verishore.secretr.pkg"
    install_location: "/"

# Windows MSI Installer
msis:
  - id: windows-installer
    builds:
      - cli
      - gui
    name: "Secretr"
    manufacturer: "Verishore LLC"
    product_version: "{{ .Version }}"
    upgrade_code: "12345678-1234-1234-1234-123456789012"
    install_dir: "Secretr"

# Windows NSIS Installer (alternative to MSI)
nsiss:
  - id: windows-nsis
    builds:
      - cli
      - gui
    name: "Secretr"
    license: "LICENSE"

# Checksums
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Homebrew for macOS CLI
brews:
  - name: secretr
    repository:
      owner: verishore
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/verishore/secretr
    description: Secretr CLI - A command-line utility
    license: MIT
    test: |
      system "#{bin}/secretr", "--version"
    install: |
      bin.install "secretr"

# Scoop for Windows CLI
scoops:
  - repository:
      owner: verishore
      name: scoop-bucket
    homepage: https://github.com/verishore/secretr
    description: Secretr CLI - A command-line utility
    license: MIT

# Changelog
changelog:
  sort: asc
  use: conventional
  groups:
    - title: "Features"
      regexp: "^feat"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix"
      order: 1

# Release configuration
release:
  github:
    owner: verishore
    name: secretr
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
